.PHONY: help up down logs build migrate ingest train test lint fmt loadtest clean

help:
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-12s\033[0m %s\n", $$1, $$2}'

up:            ## Start the whole platform
	docker compose up -d --build
	@echo "API      -> http://localhost:8000/docs"
	@echo "ML       -> http://localhost:9000/docs"
	@echo "Frontend -> http://localhost:3000"
	@echo "Grafana  -> http://localhost:3001 (admin/admin)"

down:          ## Stop everything
	docker compose down

nuke:          ## Stop everything and delete volumes
	docker compose down -v

logs:          ## Tail backend logs
	docker compose logs -f backend ml-service

migrate:       ## Run alembic migrations
	docker compose run --rm backend alembic upgrade head

revision:      ## Create a new autogenerated migration: make revision m="add x"
	docker compose run --rm backend alembic revision --autogenerate -m "$(m)"

ingest:        ## Run the full weekly ETL pipeline once
	docker compose run --rm pipeline python -m run_weekly

train:         ## Train + evaluate all models
	docker compose run --rm ml-service python -m train.train_baseline
	docker compose run --rm ml-service python -m train.train_xgboost
	docker compose run --rm ml-service python -m train.train_torch
	docker compose run --rm ml-service python -m train.evaluate

test:          ## Run test suites
	docker compose run --rm backend pytest -q
	docker compose run --rm ml-service pytest -q

lint:          ## Ruff + mypy
	ruff check backend ml-service pipeline
	ruff format --check backend ml-service pipeline

fmt:           ## Autoformat
	ruff format backend ml-service pipeline
	ruff check --fix backend ml-service pipeline

loadtest:      ## Locust against local API
	locust -f loadtest/locustfile.py --host http://localhost:8000
